New file for creating synthetic data to add more training data to the tesseract.
BloomTech-Labs/scribble-stadium-ds pull request #114
Opened 2022-02-16 19:49 UTC by MicroCapacitor

# Description

This file will be used to create synthetic data for tesseract to have more data to train on.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2022-02-16 20:11 UTC, jraval commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to increase the accuracy of the Tesseract model by finding the best preprocessing steps.](https://trello.com/c/3PndWaDa/848-as-a-developer-i-want-to-increase-the-accuracy-of-the-tesseract-model-by-finding-the-best-preprocessing-steps)

2022-02-17 03:46 UTC, gianpaolocombatti requested changes
Hey Josh - Looked at the video and the generator looks awesome, great work! Unfortunately, the data generator in this commit doesn't have any lines of code. Not sure if you uploaded from a different branch. Can you try uploading it again so I can review the actual code? I tried fetching the branch but no luck from that front either.

2022-02-17 09:20 UTC, MicroCapacitor commented
Not sure why it didn't commit with the code but I tried again and it worked. Thanks for pointing it out!

> Hey Josh - Looked at the video and the generator looks awesome, great work! Unfortunately, the data generator in this commit doesn't have any lines of code. Not sure if you uploaded from a different branch. Can you try uploading it again so I can review the actual code? I tried fetching the branch but no luck from that front either.
Not sure why it was blank, but I recommitted it and it seemed to work. Thanks for letting me know!

2022-02-17 09:21 UTC, MicroCapacitor commented
There is the whole folder of the characters and I'm not sure if I should commit all of those or not. I felt like it might be too much clutter but if you want to test I can send you the folder.

2022-02-18 01:49 UTC, nlittlepoole requested changes
@MicroCapacitor I love what you've got started here but I think what would be most helpful here is to ship this as an experiment so that others can reproduce it. The following is how I would approach doing that

1. create your own experiment folder in `structured_experiments` and name it something like `2022.02.17.synthetic_generation`
2. Copy the code I have in `2022.02.01.test` to your new folder
3. Move `synthetic_data_generator.py` into the folder
4. Modify `synthetic_data_generator.py` so that it generates more than one image (let's say 100) using different strings. Also modify it to save the `.png` and `gt.txt` files to a directory [specified via command line argumet](https://stackoverflow.com/questions/1009860/how-to-read-process-command-line-arguments)
5. Modify the Dockerfile to copy `synthetic_data_generator.py` into the image
6. Modify `experiment.sh` in your folder.  The following should replace the `setup_ground_truth.py` logic. First you want it to create a folder called `synthetic-ground-truth` in `/train/tesstrain/data/`. Then you want to run `synthetic_data_generator.py`, passing it `/train/tesstrain/data/synthetic-ground-truth` as an argument (support added in #4). This will create synthetic images in that folder . Lastly change the `MODEL_NAME` in the make command to use `synthetic` so that Tesseract uses `synthetic-ground-truth` instead of `kaggle-ground-truth`.
7. Run the docker commands in the `experiment.MD` to confirm its working
8. Update the `experiment.MD` with documentation on your experiment

2022-02-18 02:36 UTC, derekjpeters commented
![](https://github.trello.services/images/mini-trello-icon.png) [Created function for adding image files to folder with Niger's help.](https://trello.com/c/T3Tn5C6b/866-created-function-for-adding-image-files-to-folder-with-nigers-help)

2022-02-18 07:10 UTC, bofori20 approved these changes, later dismissed
Great work done. We should be able to get in synthetic data to improve the model.

2022-02-18 07:10 UTC, bofori20 commented on data/synthetic_data_creation/synthetic_data_generator.py
> +def create_char_list():
Great the script specifies file extensions.

2022-02-28 22:02 UTC, nlittlepoole requested changes
@MicroCapacitor Ok so a few more items:

1. Do you only have one image cut out per image? regardless, you should be adding these to the repository with [git-lfs](https://git-lfs.github.com/). We don't want to pollute the repository with big image files.
2. A lot more fleshed out of an experiment.MD file. This is what future cohorts are going to use to really understand the value of what you have done here. Some questions I'd love to see answered are what is the approach for generating new images and where do you find it in the code? (methodology) What are the theoretical limitations of this approach? What were the training results for tesseract? What can we conclude about using synthetic data from those test results? is it viable? are there limitations? This is the science part of data science that we don't want to lose.

2022-02-28 22:02 UTC, nlittlepoole commented on structured_experiments/2022.02.17.synthetic_generation/experiment.sh
> +python synthetic_data_generator.py /train/tesstrain/data/synthetic-ground-truth
you need to add a line between 1 and 2 and put `mkdir -p /train/tesstrain/data/synthetic-ground-truth` there. If you are running this from a brand new clean clone of the repo then you won't have the `synthetic-ground-truth` folder. You can't commit empty folders to git so this command will make sure the folder exists before running your generations script. The `-p` flag means it won't fail if the folder does happen exist already like it likely does in your `data/` folder.

2022-02-28 22:02 UTC, nlittlepoole commented on structured_experiments/2022.02.17.synthetic_generation/synthetic_data_generator.py
> +for pair in list_of_string_pairs:
fyi you can do `for file_name, text_data in list_of_string_pairs:`

2022-02-28 22:02 UTC, nlittlepoole commented on structured_experiments/2022.02.17.synthetic_generation/setup_ground_truth.py
> +import csv
you can delete this file since you aren't using it in your experiment

2022-02-28 22:37 UTC, MicroCapacitor commented on structured_experiments/2022.02.17.synthetic_generation/experiment.sh
> +python synthetic_data_generator.py /train/tesstrain/data/synthetic-ground-truth
Added such line. Appreciate you typing it out for me!

2022-02-28 22:37 UTC, MicroCapacitor commented on structured_experiments/2022.02.17.synthetic_generation/synthetic_data_generator.py
> +for pair in list_of_string_pairs:
Made such change. I'm pretty sure I've seen it before but forgot about such a thing.

2022-02-28 22:37 UTC, MicroCapacitor commented on structured_experiments/2022.02.17.synthetic_generation/setup_ground_truth.py
> +import csv
Deleted since yeah, I haven't used it.

2022-03-09 02:43 UTC, JoshuaJAnderson commented
Need to figure out if the lfs urls worked on the images I added or not. Else figure out why it's not.
![Lambda_storysquadnsynthetic](https://user-images.githubusercontent.com/79718621/157362425-5b10610b-63ea-4f5b-8e13-a98ccdd032e1.png)
Ran locally with files in story ground truth. Going to do a few more tests before comparing results.

2022-03-11 02:04 UTC, nlittlepoole approved these changes, later dismissed
:shipit:

2022-03-22 23:13 UTC, jinjahninjah approved these changes, later dismissed
Awesome work Joshua! :shipit:

2022-03-22 23:16 UTC, jinjahninjah approved these changes

2022-03-23 08:44 UTC, nlittlepoole approved these changes
👍

2022-03-23 14:25 UTC, merged