Feature/experiments
BloomTech-Labs/scribble-stadium-ds pull request #116
Opened 2022-02-22 23:38 UTC by TashaSkyUp

# Description

Replace with description of PR

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2022-02-26 17:19 UTC, MicroCapacitor requested changes

2022-02-26 17:19 UTC, JoshuaJAnderson commented on structured_experiments/data_training_pipeline_experiments/story_photo_transformer_experiments/experiment.md
> +1) does_synthetic_data_improve_mae.ipynb will test, "Training a 3 layer fully connected network on synthetic data first will improve MAE on user generated data."
Maybe change the different bullet/list types so there isn't a bunch of numbers which could cause slight confusion. Could try "A) 1) a)" or "1) 1-1) 1-1-1)"

2022-03-01 16:50 UTC, MicroCapacitor approved these changes

2022-03-01 18:16 UTC, jinjahninjah approved these changes
Very intriguing Tasha! I love these experiments, I was particularly interested in the synthetic data and it's affect on the MAE. The only feedback I would give is that it's a rather big PR, definitely chock full of goodies though.

2022-03-01 18:16 UTC, merged