Train experiment with kaggle dataset
BloomTech-Labs/scribble-stadium-ds pull request #118
Opened 2022-02-23 05:25 UTC by bofori20

# Description

Train model with kaggle dataset for baseline

## Type of change
- [ *] New feature (non-breaking change which adds functionality)

## Change Status
- [*] Complete, tested, ready to review and merge

## Has This Been Tested
- [ *] Not necessary

## Checklist
- [ *] There are no merge conflicts

2022-02-24 03:12 UTC, MicroCapacitor requested changes

2022-02-24 03:12 UTC, JoshuaJAnderson commented on structured_experiments/2022.02.17.test/experiment.MD
> +TODO: Create Template
Line from the template. Might wanna remove it.

2022-02-24 03:12 UTC, JoshuaJAnderson commented on structured_experiments/2022.02.17.test/experiment.MD
> +- Run `docker-compose -f docker-compose.yml build train && docker-compose -f structured_experiments/2022.02.01.test/docker-compose.yml up --build train_test_experiment` to train a tesseract model usi
Need to change the .yml directory to the one you've made.

2022-02-24 03:21 UTC, jraval requested changes
Hi, if you could change the template like Josh said and I'm not seeing the description for this test, I see the title but no description.  I think we saw the accuracy it was much better than the baseline, double check with TPM and our mentors but if you write up something short, I think it would be helpful.  It was really good that you did this and we can use this as a jumping off point.  Thanks.

2022-02-24 19:58 UTC, nlittlepoole requested changes
@bofori20 you need to track less of these files. I'd look at this stackoverflow [question for instructions.](https://stackoverflow.com/questions/12481639/remove-files-from-git-commit)

2022-02-24 19:58 UTC, nlittlepoole commented on .gitattributes
> +*.box filter=lfs diff=lfs merge=lfs -text
we don't want to be tracking `.box` or `.lstmf` files as these are artifacts generated by tesseract, not training data

2022-02-28 07:47 UTC, bofori20 commented on structured_experiments/2022.02.17.test/experiment.MD
> +- Run `docker-compose -f docker-compose.yml build train && docker-compose -f structured_experiments/2022.02.01.test/docker-compose.yml up --build train_test_experiment` to train a tesseract model usi
Thanks for catching that.

2022-02-28 07:52 UTC, bofori20 commented on structured_experiments/2022.02.17.test/experiment.MD
> +TODO: Create Template
@nlittlepoole, I have made changes to it. Would like to know your thoughts on how the results was presented

2022-03-01 15:22 UTC, nlittlepoole submitted a review, later dismissed
:shipit:

2022-03-01 16:51 UTC, MicroCapacitor approved these changes, later dismissed

2022-03-02 03:00 UTC, james-caldwell1981 requested changes
I'm going to agree with Niger here on the number of files tracked.
Otherwise, I like your results and methodology.

2022-03-02 03:24 UTC, bofori20 commented on .gitattributes
> +*.gt.txt filter=lfs diff=lfs merge=lfs -text
@james-caldwell1981 I already made the requested changes.

2022-03-02 04:02 UTC, bofori20 commented on structured_experiments/2022.02.17.test/experiment.MD
>  - Run `docker-compose -f docker-compose.yml build train && docker-compose -f structured_experiments/2022.02.17.test/docker-compose.yml up --build train_test_experiment` to train a tesseract model usi
@jraval requested changes have been made.

2022-03-04 02:20 UTC, nlittlepoole approved these changes
:shipit:

2022-03-23 15:21 UTC, jinjahninjah approved these changes
:shipit:

2022-03-25 01:33 UTC, jraval approved these changes
Changes requested were minor, I witnessed the training of this model and the results.  I believe it's ready for approval.

2022-03-25 01:51 UTC, james-caldwell1981 approved these changes
This is great progress on training the model as well as addressing the large number of files needed to do so.

2022-04-14 15:20 UTC, closed without merging