default API to tesseract and cleanup
BloomTech-Labs/scribble-stadium-ds pull request #126
Opened 2022-04-28 02:17 UTC by kathrynhodges

# Description

Replace with description of PR

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [x] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2022-05-06 01:52 UTC, jinjahninjah requested changes
Great job cleaning up some PEP8 issues! The only changes I have for you are in the in-line comments. Once those changes are done, we should be good to go 👍

2022-05-06 01:52 UTC, jinjahninjah commented on ocr_performance/google_tesseract_transcripts.py
> +    if __name__ == '__main__':
for this indent, did you want it to be a part of the transcribe_all() function? If not, just remove it and de-indent lines 89 -101

2022-05-06 01:52 UTC, jinjahninjah commented on ocr_performance/google_tesseract_transcripts.py
> +    if args.engine == TesseractAPI(args, language):
Since you have language in your args on 99, you don't need to parameterize it as it will throw an unresolved reference error.

2022-05-06 01:52 UTC, jinjahninjah commented on ocr_performance/google_tesseract_transcripts.py
> +    else args.engine == GOOGLE:
This one is throwing a syntax error

2022-05-06 03:51 UTC, jinjahninjah requested changes
Overall, great job! Just re-indent lines 87 - 117 and you should be good to go 👍

2022-05-12 16:11 UTC, jinjahninjah requested changes
I'm so sorry Kathryn for being so confusing! in order for this to run, we need to remove all indentation from `if __name__ == '__main__' `

The inline comments gives an example. Once this is fixed it's good to go 👍

2022-05-12 16:11 UTC, jinjahninjah commented on ocr_performance/google_tesseract_transcripts.py
> +    if __name__ == '__main__':
Just bring the "if__name__ == '__main__'" part all the way to the left so it's not indented at all, you should be good to go 👍  

I'm sorry for being so confusing! The following is what it should look like 👍 

```
if __name__ == '__main__':
    parser = ArgumentParser()
    parrser.add_argument('-e', '--engine', ...
```

2022-05-17 02:55 UTC, caitlinkermen approved these changes, later dismissed
I do not see any issues with this

2022-05-17 03:05 UTC, ashtilawat23 commented
Loom video?

2022-05-22 18:38 UTC, jinjahninjah approved these changes

2022-05-22 18:40 UTC, jinjahninjah requested changes
In addition to a Loom video, just gives us a quick description about the PR and what it accomplishes 👍

2022-06-26 21:34 UTC, kathrynhodges commented
Loom Video https://www.loom.com/share/cb6413ab074b4fda8e5bdd450a730153

2022-06-26 21:51 UTC, jinjahninjah submitted a review, later dismissed

2022-06-26 22:27 UTC, jinjahninjah approved these changes

2022-08-19 16:12 UTC, caitlinkermen approved these changes
All the changes made look to be corrections in spelling, capitalization and verbiage. After reading through the document I do not see any more changes that need to be made.

2022-09-01 20:37 UTC, merged