Added input type validation to the beginning of the histogram function.
BloomTech-Labs/scribble-stadium-ds pull request #19
Opened 2021-06-15 02:17 UTC by thomasj-s

# Histogram function input type validation

[Test endpoint: `viz/histograph`](https://trello.com/c/l4arGU8p)

---

### Location:

app/api/utils/visualizations/histogram.py

---

### Details:

1. This was added as redundancy to insure that the input types match the specified types outlined in the 'HistogramRequest' BaseModel.  Now, if there are any input discrepancies, the function will return the error message before the function finishes running. 

---

### Committed Features:
1. Added input type validation to the beginning of the histogram functions.

---

### Any Issues:
1. No issues.

2021-06-15 05:25 UTC, jmmiddour commented on app/utils/visualizations/histogram.py
> +'''
I agree with adding the edge cases to this file for testing but I do not think they need to be in function format. You did a lot of work here and it looks great but the actual testing logic is what we are writing in the test file. If you want to get with me, I can explain my thoughts on this in more detail. This was a great idea though if we did not have the testing file set up.

2021-06-16 23:45 UTC, jmmiddour commented on app/utils/visualizations/histogram.py
> +'''
Thank you for clarifying why you added the functions in this way.

2021-06-17 03:25 UTC, jeremy-jewett approved these changes, later dismissed
This was quite thoroughly done.  Except for the commented code, nicely done!

2021-06-17 04:02 UTC, jmmiddour approved these changes, later dismissed
The comments make it easier to understand what is happening with this code. You did a great job giving explanations on your code and with the testing logic.

2021-06-17 17:51 UTC, ToddDiFronzo submitted a review, later dismissed
Looks like a lot in here but from what I can follow, it looks good.

2021-06-18 00:14 UTC, jproctor-rebecca requested changes
please resolve merge conflicts

2021-06-22 00:08 UTC, jmmiddour approved these changes
Merge conflicts should be cleared now and this is ready to be merged.

2021-08-06 01:41 UTC, jrslagle approved these changes

2021-08-11 01:51 UTC, jproctor-rebecca approved these changes, later dismissed

2021-08-11 01:51 UTC, jproctor-rebecca commented on app/utils/visualizations/histogram.py
> +  '''
I really appreciate how well commented your code is.  Thank you.

2021-08-11 01:51 UTC, jproctor-rebecca commented on app/utils/visualizations/histogram.py
> +    # This returns input errors if any exist and stops the function.
This clarification adds value.  Thank you for the revision.

2021-11-10 02:08 UTC, closed without merging