Created ReadMe markdown.
BloomTech-Labs/scribble-stadium-ds pull request #26
Opened 2021-06-18 02:20 UTC by jeremy-jewett

---

[Related Trello Card](https://trello.com/c/ZOQ4Zh5E)

---

### Location:

-app/tests/README.md

---

### Details:

1. Created README for future developers

---

### Committed Features:
1. Creation of file

---

### Any Issues:
1. None

2021-06-21 23:00 UTC, jmmiddour requested changes

2021-06-21 23:00 UTC, jmmiddour commented on app/tests/README.md
> +[Documentation for Unittest](https://docs.python.org/3/library/unittest.html)
Just need a space here to separate the links for the documentation. Otherwise, looks great.

2021-06-22 00:48 UTC, jmmiddour approved these changes
Everything looks good and is ready to be merge.

2021-06-22 01:19 UTC, ToddDiFronzo approved these changes
Informative and concise

2021-08-06 01:20 UTC, jrslagle approved these changes

2021-08-11 01:39 UTC, jproctor-rebecca approved these changes
Thank you for resolving the previous comments.

2021-10-24 07:53 UTC, ike-okonkwo approved these changes
Testing suite documentation

2021-10-24 07:53 UTC, merged